name: Build and Dispatch Artifact
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build artifact
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: poivre-library
          path: poivre.so
      - name: Dispatch event to chaudiere
        uses: repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_CHAUDIERE_PAT }}
          repository: pauldardeau/chaudiere
          event: artifact_ready
          client_payload: '{"artifact_name": "poivre-library", "run_id": "${{ github.run_id }}"}'
