name: Build and Dispatch Artifact
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build artifact
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: poivre-library
          path: poivre.so
      - name: Dispatch event to chaudiere
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ poivre-token.pat }}
          repository: pauldardeau/chaudiere
          event-type: poivre-build
